adonisjs/assembler

commands/Serve.ts, src/BuildWatcher/index.ts, src/Watcher/index.ts
Make watcher respect excluded directories set in configuration file
Right now watcher does not care about excluded directories set in tsconfig.json file, since it has hardcoded values to ignore node_modules and build destination.
This PR will fix it and make watcher read exclude list from config
What types of changes does your code introduce?
Configuration has three identical arrays that all would work for it:
`config.configFileSpecs.excludeSpecs`
`config.configFileSpecs.validatedExcludeSpecs`
and 
`config.raw.exclude`
Used the last one since this was only one that didn't throw TS error (`config.configFileSpecs` does not exist according to TS), but I'm unsure if this is the best one to use.
=> feat(watcher): accept poll flag for polling file system changes

package.json, src/RcFile/index.ts, test/make-command.spec.ts, test/make-controller.spec.ts, test/make-exception.spec.ts, test/make-listener.spec.ts, test/make-middleware.spec.ts, test/make-preloaded-file.spec.ts, test/make-provider.spec.ts, test/make-validator.spec.ts, test/make-view.spec.ts
It is used to bypass the require cache, but this is not necessary as we
can just read the JSON files using fs-extra.
`import-fresh` uses a deprecated Node.js API. This is why I suggest to remove it.
Refs: https://nodejs.org/dist/latest-v15.x/docs/api/deprecations.html#DEP0144
=> fix: remove import-fresh dependency

commands/Build.ts, src/Compiler/index.ts, src/Ts/index.ts, test/compiler.spec.ts
This allows to specify a different tsconfig file for the production
build. For example, that file can extend the main tsconfig.json to
ignore test files.
=> feat: add support for --tsconfig build flag

.gitignore
This prevents VS Code from detecting changes in the directory while the
tests are running.
=> chore: add temporary test directory to .gitignore

src/Manifest/index.ts, test/compiler.spec.ts
Now that Ace correctly exits with code 1 on error, there is no need to
check stderr. This also prevents us from interpreting output from
deprecation warnings as manifest generation errors.
=> refactor: simplify generate:manifest error handling

src/AssetsBundler/index.ts
Killing server with CTRL-C in dev mode in Windows leaves webpack-dev-server running on port 8080 and
never releases it, making it impossible to start up again with `node ace serve -w` because port 8080 is already in use.
Have to use `Get-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess` to find the proccess ID and then kill it with `Stop-Process -ID ID_HERE -Force`
Fixes https://github.com/adonisjs/core/issues/2562
=> Webpack dev server not beeing killed by CTRL+C in Windows

templates/command.txt
A simple reminder for something that should be more clear
What types of changes does your code introduce?
=> Remember user to call generate:manifest

commands/Make/Controller.ts
This PR adds `Api` to the `formIgnoreList` array to avoid controllers named `Api` being pluralized. This changes comes after a [request on the Discord server](https://discord.com/channels/423256550564691970/434251922934071296/930831394551246858).
What types of changes does your code introduce?
I haven't seen any tests or documentation related to this, let me know if there is something missing.
=> fix: avoid Api getting pluralized

templates/controller.txt, templates/event-listener.txt, templates/middleware.txt, templates/provider.txt, templates/resource-controller.txt, templates/self-handle-exception.txt, templates/validator.txt
Hey! 👋🏻 
Since TypeScript 3.8 we can use `import type` instead of `import` for anything only type related.
> `import type` only imports declarations to be used for type annotations and declarations. It **always** gets fully erased, so there’s no remnant of it at runtime. Similarly, `export type` only provides an export that can be used for type contexts, and is also erased from TypeScript’s output.
=> refactor(templates): use import type when possible

src/Test/process.ts
For example, the following command : 
`node ace test --tags=tag1,tag2 --timeout 600 unit`
Produced the following error: 
`Unrecognized suite "tag2". Make sure to define it in the config first`
If I did a console.log of `filters` that was passed to execa, then I got this result 
`[ '--timeout', 60, '--tags', 'tag1, 'tag2', 'unit' ]`
So I redid a pass on the filters processing and everything seems to work fine.
I will migrate to the latest version of Japa and add some tests on this in the next PR.
=> fix: array filters passed to TestProcess were not processed properly

commands/Test.ts
Yop!
Just added the missing `--groups` flag to the `ace test` command
=> feat(test): add `--groups` flag

templates/tests/bootstrap.txt
When strict mode was enabled, the types for the different values exported in bootstrap.txt template were incorrect : 
For example, type of `export const reporters` was `ReporterContract[] | undefined`.
=> fix: incorrect test/bootstrap.txt typing

package.json, src/bundler.ts, tests/bundler.spec.ts
As you saw, cpy has had some breaking changes and they've changed their APIs. So if we follow their changelog, then you seem to have made the change the right way. 
However, it seems to doesn't work as expected :
For a metaFiles pattern `/resources/views/**.*.edge` and the given directory structure : 
```
resources/
views/
view.edge
admin/
admin.edge
```
After copying, we will have this result in the ./build folder:
```
build/
view.edge
admin/
admin.edge
```
I don't know why, I've tried a lot of different things to make it works but I think that it's a bug on the cpy side. so I suggest we just rollback temporarily. not super important I think
Also added a test that check we keep the original directory structure
=> fix: metafiles copying

src/code_transformer/rc_file_transformer.ts
Hey there! 👋🏻 
This PR is fixing an issue with the `addCommand` method. We were not using the correct property name.
We will have to revisit our test suites since that kinds of errors are currently not caught.
=> fix(transformer): addCommand method was not using correct property name

src/code_transformer/main.ts, tests/__snapshots__/code_transformer.spec.ts.cjs, tests/code_transformer.spec.ts
`addJapaPlugin` will modify the `boostrap/tests.ts` file to add a new plugin to the `export const plugins` array.
Can be used as follows: 
```ts
await codemods.addJapaPlugin('sessionApiClient(app)', {
module: '@adonisjs/session/plugins/api_client',
identifier: 'sessionApiClient',
isNamed: true,
})
```
The first parameter is the text to be inserted into the array of plugins
The second parameter is the import to add to the top of the file. This can be a named import or not.
The above code will result in : 
```ts
import app from '@adonisjs/core/services/app'
import { assert } from '@japa/assert'
import { sessionApiClient } from '@adonisjs/session/plugins/api_client'
export const plugins: Config['plugins'] = [
assert(),
sessionApiClient(app)
]
```
Also added two settings for all …
=> Add `addJapaPlugin` to Codemods

package.json, src/bundler.ts, tests/bundler.spec.ts
Port of this PR to the assembler : https://github.com/adonisjs/core/pull/4290
Bundler will automatically detect the package manager used by the project, if not specified explicitly
=> Bundler automatically detect used package manager

README.md, src/code_transformer/main.ts, tests/code_transformer.spec.ts
New `addVitePlugin` method. Same API as `addJapaPlugin` and works in the same way.
Adds a plugin to the `vite.config.ts` file. 
Will be useful for configuring `@adonisjs/inertia`
=> feat: add `addVitePlugin` method

src/code_transformer/main.ts
**PR is targetting #73 branch**
i've made the `project` property public. this corresponds to the tsmorph instance.
the aim is that someone using this class will be able to apply and develop their own codemods
```ts
const transformer = new CodeTransformer(appRoot)
transformer.project // I can now apply all the modifications I want via ts-morph
```
I'm thinking in particular of codemods that could be applied from `configure.ts` but also too specific to have higher-level APIs in the CodeTransformer
=> refactor: make `project` public in `CodeTransformer`

package.json, src/bundler.ts, src/dev_server.ts, src/hooks.ts, src/types.ts, tests/bundler.spec.ts
Added assembler hooks that was added in the RC File since this release: https://github.com/adonisjs/application/releases/tag/v8.1.0 
Can be used like that :
```ts
new DevServer({
hooks: {
onDevServerStarted: () => {},
onSourceFileChanged: () => {},
}
})
new Bundler({
hooks: {
onBuildCompleted: () => {},
onBuildStarting: () => {},
}
})
```
=> feat: add bundler and devserver hooks

package.json, src/dev_server.ts, src/types.ts, tests/dev_server.spec.ts
Integrate hot-hook into the assembler
Basically, if the --hmr flag is passed, we spawn the Node subprocess with the `--import=hot-hook/register` hook.
We intercept received messages sent by Hot Hook from the subprocess: 
- If it's a full reload message, clear screen + log + restart http server
- If it's an invalidation message (i.e. from HMR), then just a log
=> feat: hot-hook integration

src/dev_server.ts, tests/run.spec.ts
The `file system watcher` message that appears when you start the Adonis server is no longer really appropriate now that we have HMR. Because we have a `File System Watcher: disabled` which is displayed when we are in HMR mode. 
Looks weird
So I've changed the message. But not really sure of the words :
- With nothing, it will display `Mode: Non-Watching`.
- `--watch` will display: `Mode: Watching`
- `--hmr` will display: `Mode: HMR`
if you guys have something better lemme know
=> refactor: update ready message

src/bundler.ts, tests/bundler.spec.ts
[adonisjs/core#4568](https://github.com/adonisjs/core/issues/4568)
This PR adds support for yarn berry into assembler (required to then add it to core).
It replaces `lockFile` in `SUPPORT_PACKAGE_MANAGERS` because yarn berry also need some other metadata files, but it might be useful for other package managers too.
Not sure there is documentation to be updated, it should just make it work out of the box for yarn berry.
=> feat: yarn berry support
